version: '3.1'

services:
  hapi:
    build:
      context: .
      dockerfile: Dockerfile
    restart: always
    container_name: hapi
    # depends_on:
    #   - "redis"
    #   - "rabbit"
    environment:
      - PORT=9099
      - MQ_HOST=rabbit
      - MQ_PORT=5672
      - MQ_USER=rabbitmq
      - MQ_PASSWORD=rabbithole
      - REDIS_ADDR=redis:6379
      - QUEUE=credstoreIn
    ports:
      - "9099:9099"

  redis:
    image: "redis:latest"
    restart: always
    container_name: redis
    ports: 
      - "6379:6379"

  rabbit:
    image: "rabbitmq:3-management"
    restart: always
    container_name: rabbit
    environment:
      RABBITMQ_DEFAULT_USER: "rabbitmq"
      RABBITMQ_DEFAULT_PASS: "rabbithole"
      RABBITMQ_DEFAULT_VHOST: "/"
    ports:
      - "15672:15672"
      - "5672:5672"
    labels:
      NAME: "rabbitmq1"
